modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"


[[mods]]
modId="bca_food_mod"
version="1.0"
displayName="BCA Mod"
logoFile="logo.png"
authors="Evan Ciccarelli, Leo Ciccarelli, Christopher Kalish, and Jeremy Kurian"
description='''
A mod that adds more foods for CS fair 2021
'''
[[dependencies.bca_food_mod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bca_food_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1)"
    ordering="NONE"
    side="BOTH"
